context:
  version: "1.15.0"

package:
  name: kitops
  version: ${{ version }}

source:
  url: https://github.com/kitops-ml/kitops/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 956a3d526eb45848e66a49089fcc7867c7df4c2e019a3126219e8f1d7163f7e5

build:
  number: 0
  script:
    - go-licenses save . --save_path=library_licenses
    - if: unix
      then:
        - BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        - SHORT_COMMIT_HASH="$(curl -s "https://api.github.com/repos/kitops-ml/kitops/commits/v${{ version }}" | jq -r '.sha' | cut -c 1-7)"
        - go build -v -o "$PREFIX"/bin/kit -ldflags="-s -w -X github.com/kitops-ml/kitops/pkg/lib/constants.Version=${{ version }} -X github.com/kitops-ml/kitops/pkg/lib/constants.BuildTime=${BUILD_TIME} -X github.com/kitops-ml/kitops/pkg/lib/constants.GitCommit=${SHORT_COMMIT_HASH}" -trimpath .
        # generate shell completions
        - if: build_platform == host_platform
          then:
            - mkdir -p "$PREFIX"/share/bash-completion/completions "$PREFIX"/share/fish/vendor_completions.d "$PREFIX"/share/zsh/site-functions
            - '"$PREFIX"/bin/kit completion bash > "$PREFIX"/share/bash-completion/completions/kit'
            - '"$PREFIX"/bin/kit completion fish > "$PREFIX"/share/fish/vendor_completions.d/kit.fish'
            - '"$PREFIX"/bin/kit completion zsh  > "$PREFIX"/share/zsh/site-functions/_kit'
    - if: win
      then:
        - for /f "usebackq delims=" %%T in (`powershell -Command "[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ')"`) do set BUILD_TIME=%%T
        - for /f "usebackq delims=" %%T in (`powershell -Command "((Invoke-RestMethod 'https://api.github.com/repos/kitops-ml/kitops/commits/v${{ version }}').sha).Substring(0, 7)"`) do set SHORT_COMMIT_HASH=%%T
        - go build -v -o "%LIBRARY_BIN%"\kit.exe -ldflags="-s -w -X github.com/kitops-ml/kitops/pkg/lib/constants.Version=${{ version }} -X github.com/kitops-ml/kitops/pkg/lib/constants.BuildTime=%BUILD_TIME% -X github.com/kitops-ml/kitops/pkg/lib/constants.GitCommit=%SHORT_COMMIT_HASH%" -trimpath .
        # generate shell completions
        - if: build_platform == host_platform
          then:
            - mkdir "%LIBRARY_PREFIX%"\share\bash-completion\completions
            - mkdir "%LIBRARY_PREFIX%"\share\fish\vendor_completions.d
            - mkdir "%LIBRARY_PREFIX%"\share\zsh\site-functions
            - '"%LIBRARY_BIN%"\kit.exe completion bash > "%LIBRARY_PREFIX%"\share\bash-completion\completions\kit'
            - '"%LIBRARY_BIN%"\kit.exe completion fish > "%LIBRARY_PREFIX%"\share\fish\vendor_completions.d\kit.fish'
            - '"%LIBRARY_BIN%"\kit.exe completion zsh  > "%LIBRARY_PREFIX%"\share\zsh\site-functions\_kit'

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - kit --help
      - kit version
  - package_contents:
      bin:
        - kit
      files:
        - if: unix and build_platform == host_platform
          then:
            - share/bash-completion/completions/kit
            - share/fish/vendor_completions.d/kit.fish
            - share/zsh/site-functions/_kit
        - if: win and build_platform == host_platform
          then:
            - Library/share/bash-completion/completions/kit
            - Library/share/fish/vendor_completions.d/kit.fish
            - Library/share/zsh/site-functions/_kit
      strict: true

about:
  summary: An open source MLOps tool for packaging, versioning, and sharing AI/ML projects
  description: |
    KitOps is an open source tool that allows to package, version, share, and
    deploy AI/ML models and their associated artifacts using familiar DevOps
    practices and OCI standards. It facilitates collaborative work on
    self-hosted AI/ML models and makes sharing, automating, and deploying those
    models as simple as managing containerized apps.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  homepage: https://kitops.org
  documentation: https://kitops.org/docs
  repository: https://github.com/kitops-ml/kitops

extra:
  recipe-maintainers:
    - salim-b
